name = "LowRankMethods"
uuid = "a03e3c17-9662-4f35-944a-00ef85d23e84"
version = "0.1.0"
authors = ["Valentina Schüller <valentina.schueller@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.12.0"
